export const EXCHANGE_URL = 'http://data.fixer.io/api/latest';
export const ACCESS_KEY = 'a02866acf655981456a52f9f1f94e4da';
export const SUPPORTED_CURRENCIES = 'EUR,USD,BRL,CAD,GBP,JPY';
export const CURRENCY_SYMBOLS = {
    USD: 'US$',
    BRL: 'R$',
    CAD: '$',
    GBP: '£',
    JPY: '¥',
    EUR: '€',
};

export const API_BASE_URL = 'http://localhost:8080/';
export const API_CATEGORIES = 'categories';
export const API_PRODUCTS = 'products';
export const DELETE_PATH = 'delete';
export const EDIT_PATH = 'edit';
export const CREATE_PATH = 'create';

export const CATEGORY_LIST_FETCH_SUCCESS = 'CATEGORY_LIST_FETCH_SUCCESS';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_SELECTED_SUCCESS = 'CATEGORY_SELECTED_SUCCESS';
export const CATEGORY_ADD_NEW_SUCCESS = 'CATEGORY_ADD_NEW_SUCCESS';

export const PRODUCTS_LIST_FETCH_SUCCESS = 'PRODUCTS_LIST_FETCH_SUCCESS';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_ADD_NEW_SUCCESS = 'PRODUCT_ADD_NEW_SUCCESS';

export const CURRENCY_LIST_FETCH_SUCCESS = 'CURRENCY_LIST_FETCH_SUCCESS';
