export const API_BASE_URL = 'http://localhost:8080/';
export const API_CATEGORIES = 'categories';
export const API_PRODUCTS = 'products';
export const DELETE_PATH = 'delete';
export const EDIT_PATH = 'edit';
export const CREATE_PATH = 'create';

export const CATEGORY_LIST_FETCH_SUCCESS = 'CATEGORY_LIST_FETCH_SUCCESS';
export const CATEGORY_CREATE_SUCCESS = 'CATEGORY_CREATE_SUCCESS';
export const CATEGORY_DELETE_SUCCESS = 'CATEGORY_DELETE_SUCCESS';
export const CATEGORY_UPDATE_SUCCESS = 'CATEGORY_UPDATE_SUCCESS';
export const CATEGORY_SELECTED_SUCCESS = 'CATEGORY_SELECTED_SUCCESS';

export const PRODUCTS_LIST_FETCH_SUCCESS = 'PRODUCTS_LIST_FETCH_SUCCESS';
export const PRODUCT_CREATE_SUCCESS = 'PRODUCT_CREATE_SUCCESS';
export const PRODUCT_DELETE_SUCCESS = 'PRODUCT_DELETE_SUCCESS';
export const PRODUCT_UPDATE_SUCCESS = 'PRODUCT_UPDATE_SUCCESS';
